import type { NextPage } from 'next'
import Head from 'next/head'

import { faPlus, faPaperPlane } from '@fortawesome/free-solid-svg-icons'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'

import { ChatList } from "../../components/Chat/List";
import { SearchInList } from "../../components/Chat/SearchInList";
import { Messages } from "../../components/Chat/Content/Messages";
import { Header as ContentHeader } from "../../components/Chat/Content/Header";
import {ChatContext, ChatContextWrapper, useChatContext} from "../../components/Chat/Context";
import {MessageForm} from "../../components/Chat/Content/MessageForm";
import {useContext} from "react";
import {Content} from "../../components/Chat/Content";

// create random user
const user = {
    id:  new Date().getTime().toString(),
    username: new Date().getTime().toString()
};

const ChatRoom: NextPage = () => {

    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="">
                <div className="bg-blue-800 fixed">
                    <img className="w-screen h-screen opacity-90" src="/macos-big-sur-apple-layers.jpeg" />
                </div>
                <ChatContextWrapper user={user}>
                    <div className="inner fixed w-full h-full z-10">
                        <div className="p-8 w-full h-full">
                            <div className="relative w-full h-full overflow-hidden rounded-smooth border border-tiny">
                                {/*<div className="absolute bg-smooth filter blur-md w-full h-full transform scale-105" />*/}
                                <div className="w-full h-full flex">
                                    {
                                        false && (
                                            <div className="left-side relative h-full max-w-md overflow-hidden border-r border-tiny bg-chat-list">
                                                <div className="w-full h-full p-8 z-10 relative flex flex-col">
                                                    <h3 className="text-3xl text-white">Recent</h3>
                                                    <div className="mb-3"></div>
                                                    <div className="flex">
                                                        <div className="w-full">
                                                            <SearchInList />
                                                        </div>
                                                        <div className="flex items-center justify-center ml-3">
                                                            <div className="w-10 p-2 bg-gray-900 rounded cursor-pointer">
                                                                <FontAwesomeIcon icon={faPlus} color="white" />
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div className="mb-2" />
                                                    <div className="overflow-y-auto">
                                                        <ChatList />
                                                    </div>

                                                </div>
                                            </div>
                                        )
                                    }
                                    <div className="content relative w-full h-full">
                                        {/*<div className="h-30 absolute top-0 w-full overflow-hidden">*/}
                                        {/*    <div className="bg-smooth filter blur-sm w-full p-10 transform scale-105" />*/}
                                        {/*</div>*/}
                                        <Content />
                                    </div>
                                    {/*<div className="right-side"></div>*/}
                                </div>
                            </div>
                        </div>
                    </div>
                </ChatContextWrapper>
            </div>
        </div>
    )
}

export default ChatRoom
