import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div className="w-full h-full">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <div className="flex items-center justify-center w-full h-full">
            <h3 className="text-4xl">
                Welcome
            </h3>
        </div>

    </div>
  )
}

export default Home
